---
networks:
  tsdproxy_net:
    external: true
    name: tsdproxy_net

# Media Server Compose for TrueNAS Stack
# Mount Path:
## App Data: ${APPCONFIG_DIR}
## Media path: ${MEDIA_DIR}/Media
## Downloads path: ${MEDIA_DIR}/Downloads

# Ports and IP
# Jellyfin: 172.18.0.9
# - 8096:8096
# - 8920:8920 #optional
# - 7359:7359/udp #optional
# - 1900:1900/udp #optional
# Jellyseerr: 172.18.0.10
# - 5055:5055
# Komga: 172.18.0.14
# - 25600:25600
# Suwayomi: 172.18.0.15
# - 4567:4567
# QBittorrent: 172.18.0.20
# - 8080:8080
# - 6882:6881
# - 6882:6881/udp

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=568
      - PGID=568
      - TZ=${TZ}
      # - JELLYFIN_PublishedServerUrl=http://192.168.0.5 #optional
    volumes:
      - ${APPCONFIG_DIR}/Jellyfin:/config
      - ${MEDIA_DIR}/Media:/data/media
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "jellyfin"
      tsdproxy.container_port: "8096"
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=568
      - PGID=568
      - LOG_LEVEL=debug
      - TZ=${TZ}
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "jellyseerr"
      tsdproxy.container_port: "5055"
    ports:
      - 5055:5055
    volumes:
      - ${APPCONFIG_DIR}/Jellyseerr:/app/config
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=568
      - PGID=568
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${APPCONFIG_DIR}/QBittorrent:/config
      - ${MEDIA_DIR}/Downloads/Torrents:/downloads #optional
    ports:
      - 8080:8080
      - 6882:6881
      - 6882:6881/udp
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "qbittorrent"
      tsdproxy.container_port: "8080"
    restart: unless-stopped

  komga:
    image: ghcr.io/gotson/komga:latest
    container_name: komga
    volumes:
      - ${APPCONFIG_DIR}/Komga/config:/config
      - ${MEDIA_DIR}/Media:/data
    ports:
      - 25600:25600
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "komga"
      tsdproxy.container_port: "25600"
    environment:
      - PUID=568
      - PGID=568
      - TZ=${TZ}
      - JAVA_TOOL_OPTIONS=-Xmx1g
    restart: unless-stopped

  kavita:
      image: jvmilazz0/kavita:latest    # Using the stable branch from the official dockerhub repo.
      container_name: kavita
      volumes:
          - ${MEDIA_DIR}/Media:/data
          - ${APPCONFIG_DIR}/Kavita/config:/kavita/config     # /kavita/config must not be changed
      environment:
          - TZ=${TZ}
          - PUID=568
          - PGID=568
      labels:
          tsdproxy.enable: "true"
          tsdproxy.name: "kavita"
          tsdproxy.container_port: "5000"
      ports:
          - "5000:5000"
      restart: unless-stopped